### ISSUE TITLE
Using VisualStudio

### ISSUE THREAD

**Issue by sshsurabhi** [microchip-pic-avr-examples/avr128db48-analog-read-serial-write-mplab-mcc#1]
Hello,

I just want to use **Microsoft VisualStudio** to develop my library creation. So, **instead of using MicrochipStudio**, how to set up the environment to write a C++ program in Visual Studio connect AVR12bDB48 curiosity nano microcontroller.

Can you people please guide me with any documents to set up the environment in **VisualStudio**? I've searched online but could not find any much useful.

Thank You.

**Comment by pic-avr-github-admin** [comment]
Hi, unfortunately we do not have a guide for Microsoft VisualStudio. 
However, we have recently released a collection of extensions for Microsoft Visual Studio Code: https://www.microchip.com/en-us/tools-resources/develop/mplab-extensions-vs-code
Hopefully these extensions are useful even if they are currently released under an early access program.
